### ISSUE TITLE
unit.inject() do nothing

### ISSUE THREAD

**Issue by davidyushkov** [node-sc2/core#8]
Currently `unit.inject` function without arguments do nothing, and the problem placed in `egine/create-units.js` in `inject` function, instead of this
```js
const [idleHatch] = units.getById(UnitType.HATCH).filter(u => u.isIdle());
```
should be
```js
const [idleHatch] = units.getByType(TownhallRace[Race.ZERG]).filter(u => u.isIdle());
```
But this solution causes another effect that any queen on run blank inject function will go to the main to inject it, though to inject nearest Hatchery has more sense.

something like this
```js
const [idleHatch] = units.getClosest(this.pos, units.getByType(TownhallRace[Race.ZERG]), 1);
```

**Comment by jkantr** [comment]
Fixed on 0.9.0-alpha.5 https://github.com/node-sc2/core/commit/417adc44c0127e89d95f1b799890dd92a22d7055
