### ISSUE TITLE
Opens a black StarCraft 2 window 

### ISSUE THREAD

**Issue by jinghao** [node-sc2/core#9]
I'm just trying out the basic worker rush.

It opens the SC2 app (Version 5.0.2 (81433)) on my MacBook running Catalina (10.15.6) but unfortunately SC2 just renders a black window. SC2 works when I open it normally to play. 

See:

<img width="1993" alt="Screen Shot 2020-08-27 at 12 09 33 PM" src="https://user-images.githubusercontent.com/602598/91484691-81c59180-e85e-11ea-8fb4-7ae85992afa5.png">

What am I missing? I've read all the docs. Thanks!

```
[jyan@jyan-mbp sc2]$ cat main.js
const { createAgent, createEngine, createPlayer } = require('@node-sc2/core');
const { Difficulty, Race } = require('@node-sc2/core/constants/enums');

const bot = createAgent({
    async onGameStart({ resources }) {
        const { units, actions, map } = resources.get();

        const workers = units.getWorkers();
        return actions.attackMove(workers, map.getEnemyMain().townhallPosition);
    }
});

const engine = createEngine();

engine.connect().then(() => {
    return engine.runGame('Blueshift LE', [
        createPlayer({ race: Race.RANDOM }, bot),
        createPlayer({ race: Race.RANDOM, difficulty: Difficulty.MEDIUM }),
    ]);
});
[jyan@jyan-mbp sc2]$ node -v
v14.8.0
```

**Comment by kristians2** [comment]
Same on windows. Considering that there's an unresolved issue from Jan 2019, I think it's safe to assume that this project has been abandoned

**Comment by alkurbatov** [comment]
@kristians2 @jinghao The last changes are in alpha, please, try with `"@node-sc2/core": "0.9.0-alpha.4",`.
Here is a working example:
https://github.com/alkurbatov/kutuzov-bot

**Comment by jkantr** [comment]
This has been working for quite awhile now on the alpha branch. 0.9.0-alpha.6 is the version you want.
